fixtures:
  repositories:
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    registry: 'https://github.com/puppetlabs/puppetlabs-registry.git'
    translate: 'https://github.com/puppetlabs/puppetlabs-translate.git'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    provision:
      repo: "https://github.com/pmcmaw/provision.git"
      ref: "5580862d3bc6ece5da31f58b9f2d4733d5bb55f4"
  symlinks:
    mdlj: "#{source_dir}"
