---
common:
  service_url: https://facade-main-6f3kfepqcq-ew.a.run.app/v1/provision

".gitlab-ci.yml":
  delete: true
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
".travis.yml":
  global_env:
    - HONEYCOMB_WRITEKEY="xxxxxxxxxxxxxxx",HONEYCOMB_DATASET="litmus tests"
  dist: trusty
  deploy_to_forge:
    enabled: false
  branches:
  - release
  user: puppet
  secure: ''
  use_litmus: false
  simplecov: true
appveyor.yml:
  environment:
    HONEYCOMB_WRITEKEY: xxxxxxxxxxxxxxx
    HONEYCOMB_DATASET: litmus tests
  use_litmus: false
  simplecov: true
Gemfile:
  optional:
    ":development":
    - gem: bolt
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.7.0')
Rakefile:
  changelog_since_tag: v1.9.0
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false

.github/workflows/nightly.yml:
  unmanaged: false
.github/workflows/pr_test.yml:
  unmanaged: false
.github/workflows/auto_release.yml:
  unmanaged: false
.github/workflows/spec.yml:
  checks: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false
