name: "manual_test"

on:
  workflow_dispatch:
  pull_request:

env:
  SERVICE_URL: https://facade-cat-2096-update-to-opentofu-1079112402178.europe-west1.run.app/v1/provision

jobs:
  Acceptance:
    name: "rhel-9"

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Activate Ruby 3.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.2"
        bundler-cache: true

    - name: Print bundle environment
      run: |
        echo ::group::bundler environment
        bundle env
        echo ::endgroup::

    - name: Provision test environment
      run: |
        bundle exec rake 'litmus:provision[provision_service,rhel-9]'
        echo ::group::=== REQUEST ===
        cat request.json || true
        echo
        echo ::endgroup::
        echo ::group::=== INVENTORY ===
        if [ -f 'spec/fixtures/litmus_inventory.yaml' ];
        then
          FILE='spec/fixtures/litmus_inventory.yaml'
        elif [ -f 'inventory.yaml' ];
        then
          FILE='inventory.yaml'
        fi
        sed -e 's/password: .*/password: "[redacted]"/' < $FILE || true
        echo ::endgroup::

    - name: Install agent
      run: |
        bundle exec rake 'litmus:install_agent[puppet7]'

    - name: Remove test environment
      if: ${{ always() }}
      continue-on-error: true
      run: |
        bundle exec rake 'litmus:tear_down'
